# Generated by Django 4.0.3 on 2022-03-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Users',
        ),
    ]
